_target_: src.models.GASATF
name: GASATF
val_top_n: 10
triangle: lower
decay_mode: lin
max_positions: 0
growth_tol: 1e-3
iters: 20
tries: 3
downvote_seen_items: true
verbose: True
rank_u: 0
rank_v: 0
rank_w: 0
seed: 42
scaling_factor: 1.0
decay: 1.0
rescaled: true