_target_: src.models.LightGCN
name: "LightGCN_fullcatalog"

rank: 0
n_layers: 0
edge_dropout: 0.0

batch_size: 2048
learning_rate: 0
regularization: 0
n_epochs: 500

foldin_epochs: 1
foldin_lr: 0.0
foldin_reg: 0

verbose: false
seed: 42
device: "auto"
n_valid: 5
patience: 3
val_top_n: 10
