_target_: src.models.MFSGD
name: "MF_SGD"
rank: 0
regularization: 0
learning_rate: 0
gamma: 0.0
n_epochs: 500
n_epochs_folding: 20
n_valid: 10
verbose: False
lambda_geo: 0
n_negatives: 0
resample_every_factor: 1.0
min_folding_epochs: 2
folding_epsilon: 1e-3
patience: 2
