- name: n_epochs
  type: int
  low: 5
  high: 100
  step: 5
- name: rank
  type: int
  low: 5
  high: 400
  step: 20
- name: learning_rate
  type: float
  log: true
  low: 1e-4
  high: 1e-1
- name: regularization
  type: float
  log: true
  low: 1e-5
  high: 1e-1