experiment_name: beauty_exp
dataset:
  path_to_data_dir: data
  name: reviews_Beauty_5
  max_sequence_length: 10
  samplers: {}
dataloader:
  train:
    batch_size: 128
    drop_last: false
    shuffle: true
  validation:
    batch_size: 256
    drop_last: false
    shuffle: false
model:
  embedding_dim: 64
  num_heads: 1
  num_layers: 2
  dim_feedforward: 64
  dropout: 0.3
  activation: gelu
  layer_norm_eps: 1.0e-09
  initializer_range: 0.02
  num_hops: 2
optimizer:
  optimizer:
    type: adam
    lr: 0.001
  clip_grad_threshold: 10.0
optimizer_fi:
  optimizer:
    type: adam
    lr: 0.0001
loss:
  local:
    predictions_prefix: local_prediction
    labels_prefix: positive
  global:
    positive_prefix: global_positive
    negative_prefix: global_negative
  fusion:
    positive_prefix: fusion_positive
    negative_prefix: fusion_negative
  contrastive:
    fst_embeddings_prefix: contrastive_fst_embeddings
    snd_embeddings_prefix: contrastive_snd_embeddings
metrics:
  ndcg@10:
    type: ndcg
    k: 10
device: "cpu"
num_epochs: 100
early_stopping_rounds: 20
