defaults:
  - dataloader
  - loss
  - general

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${model_name}__${dataset.name}__${now:%H-%M-%S}

dataset:
  path_to_data_dir: data
  name: reviews_Beauty_5
  max_sequence_length: 10

model:
  # sasrec
  embedding_dim: 128
  num_heads: 1
  num_layers: 4
  dim_feedforward: 128
  dropout: 0.4
  # mrgsrec
  num_hops: 1
  eta: 0.5870549675235889
  # other
  activation: gelu
  layer_norm_eps: 1.0e-09
  initializer_range: 0.02
  topk_k: null

optimizer:
  optimizer:
    type: adam
    lr: 0.0014002963516611
  clip_grad_threshold: 10.0

loss:
  local_coef: 0.6745027729685843
  global_coef: 0.95571105582261
  fusion_coef: 0.2062739194537569
  contrastive_coef: 0.2010478231381737
model_name: mrgsrec