defaults:
  - dataloader
  - loss
  - general

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${model_name}__${dataset.name}__${now:%H-%M-%S}

dataset:
  path_to_data_dir: data
  name: ml1m
  max_sequence_length: 10

model:
  # optuna
  embedding_dim: 64
  num_heads: 2
  num_layers: 3
  dim_feedforward: 128
  dropout: 0.2
  # mrgsrec
  num_hops: 1
  eta: 0.5657522461471146
  # other
  activation: gelu
  layer_norm_eps: 1.0e-09
  initializer_range: 0.02

optimizer:
  optimizer:
    type: adam
    lr: 0.0025367616568376

loss:
  local_coef: 0.8600577978163476
  global_coef: 0.2810029625903459
  fusion_coef: 0.4654652335776962
  contrastive_coef: 0.0373285026686398

model_name: mrgsrec