start_from: 0
experiment_name: sasrec_sports_grid
best_metric: validation/ndcg@20
dataset:
  type: sequence
  path_to_data_dir: ./data2
  name: MovieLens1M
  max_sequence_length: 10
  samplers:
    type: next_item_prediction
    negative_sampler_type: random
dataset_params: {}
dataloader:
  train:
    type: torch
    batch_size: 256
    batch_processor:
      type: basic
    drop_last: true
    shuffle: true
  validation:
    type: torch
    batch_size: 256
    batch_processor:
      type: basic
    drop_last: false
    shuffle: false
model:
  type: sasrec
  sequence_prefix: item
  positive_prefix: positive
  negative_prefix: negative
  candidate_prefix: candidates
  embedding_dim: 8
  num_heads: 2
  num_layers: 2
  dim_feedforward: 256
  activation: gelu
  layer_norm_eps: 1.0e-09
  initializer_range: 0.02
model_params:
  dropout:
  - 0.1
optimizer:
  type: basic
  optimizer:
    type: adam
    lr: 0.001
  clip_grad_threshold: 5.0
optimizer_params: {}
loss:
  type: composite
  losses:
  - type: sasrec
    positive_prefix: positive_scores
    negative_prefix: negative_scores
    output_prefix: downstream_loss
  output_prefix: loss
loss_params: {}
callback:
  type: composite
  callbacks:
  - type: metric
    on_step: 1
    loss_prefix: loss
  - type: validation
    on_step: 64
    pred_prefix: logits
    labels_prefix: labels
    metrics:
      ndcg@5:
        type: ndcg
        k: 5
      ndcg@10:
        type: ndcg
        k: 10
      ndcg@20:
        type: ndcg
        k: 20
      recall@5:
        type: recall
        k: 5
      recall@10:
        type: recall
        k: 10
      recall@20:
        type: recall
        k: 20
      coverage@5:
        type: coverage
        k: 5
      coverage@10:
        type: coverage
        k: 10
      coverage@20:
        type: coverage
        k: 20
  - type: eval
    on_step: 256
    pred_prefix: logits
    labels_prefix: labels
    metrics:
      ndcg@5:
        type: ndcg
        k: 5
      ndcg@10:
        type: ndcg
        k: 10
      ndcg@20:
        type: ndcg
        k: 20
      recall@5:
        type: recall
        k: 5
      recall@10:
        type: recall
        k: 10
      recall@20:
        type: recall
        k: 20
      coverage@5:
        type: coverage
        k: 5
      coverage@10:
        type: coverage
        k: 10
      coverage@20:
        type: coverage
        k: 20

