experiment_name: mrgsrec_sports
dataset:
  use_user_graph: false
  use_item_graph: false
  graph_dir_path: data2/Sports
  dataset:
    path_to_data_dir: data2
    name: Sports
    max_sequence_length: 10
    samplers: {}
dataloader:
  train:
    batch_size: 256
    drop_last: false
    shuffle: true
  warm_val:
    batch_size: 256
    drop_last: false
    shuffle: true
  validation:
    batch_size: 256
    drop_last: false
    shuffle: false
model:
  embedding_dim: 16
  num_heads: 2
  num_layers: 2
  dim_feedforward: 256
  dropout: 0.5
  activation: gelu
  layer_norm_eps: 1.0e-09
  initializer_range: 0.02
optimizer:
  optimizer:
    type: adam
    lr: 0.001
  clip_grad_threshold: 10.0
optimizer_fi:
  optimizer:
    type: adam
    lr: 0.0001
loss:
  local:
    predictions_prefix: local_prediction
    labels_prefix: positive
  global:
    positive_prefix: global_positive
    negative_prefix: global_negative
  fusion:
    positive_prefix: fusion_positive
    negative_prefix: fusion_negative
  contrastive:
    fst_embeddings_prefix: contrastive_fst_embeddings
    snd_embeddings_prefix: contrastive_snd_embeddings
metrics:
  ndcg@10:
    type: ndcg
    k: 10

